import { writeFile, mkdir } from "node:fs/promises"
import { join, basename } from "node:path"
import { randomUUID } from "node:crypto"
import { homedir } from "node:os"
import type { Plugin } from "@opencode-ai/plugin"
import { log } from "./logger"
import { SessionSnapshotSchema } from "./schema"

export function resolveSnapshotDir(ctx: Parameters<Plugin>[0], dateStamp: string): string {
  const humanID = process.env.OPENCODE_HUMAN_ID ?? process.env.USERNAME ?? process.env.USER ?? "unknown"
  const projectSlug = basename(ctx.directory)
  const home = homedir()
  return join(home, ".config", "opencode", "sessions", humanID, projectSlug, `${dateStamp}-runtime`)
}

export function formatDateStamp(): string {
  const now = new Date()
  const dd = String(now.getDate()).padStart(2, "0")
  const mm = String(now.getMonth() + 1).padStart(2, "0")
  const yyyy = String(now.getFullYear())
  return `${dd}${mm}${yyyy}`
}

export function buildMarkdown(status: string, sessionID: string, eventType: string, extra: Record<string, unknown>): string {
  const lines = [
    "> Generated by davercode-session-bridge plugin (runtime snapshot)",
    "",
    `# Runtime Snapshot (session ${sessionID})`,
    "",
    "## Status",
    status,
    "",
    "## Decisions",
    "- Not available from runtime event stream",
    "",
    "## Files changed",
    "- Not available from runtime event stream",
    "",
    "## Subagent outcomes",
    "- Not available from runtime event stream",
    "",
    "## Commands run",
    `- Event type: ${eventType}`,
    `- Session ID: ${sessionID}`,
    `- Extra: ${JSON.stringify(extra, null, 2)}`,
    "",
    "## Open questions",
    "- Not available from runtime event stream",
    "",
    "## Resume instructions",
    "- Snapshot generated automatically by davercode-session-bridge plugin",
    "- Consult the session event stream for full context",
  ]
  return lines.join("\n")
}

export async function writeSessionSnapshot(
  ctx: Parameters<Plugin>[0],
  sessionID: string,
  status: "idle" | "error" | "completed",
  eventProperties: Record<string, unknown>,
): Promise<void> {
  const dateStamp = formatDateStamp()
  const uuid = randomUUID()
  const dir = resolveSnapshotDir(ctx, dateStamp)
  const projectSlug = basename(ctx.directory)
  const humanID = process.env.OPENCODE_HUMAN_ID ?? process.env.USERNAME ?? process.env.USER ?? "unknown"

  const payload = {
    schemaVersion: "1.0",
    generatedBy: "davercode-session-bridge" as const,
    generatedAt: new Date().toISOString(),
    sessionID,
    eventType: status === "idle" ? "session.idle" : "session.error",
    projectSlug,
    humanID,
    status,
    extra: eventProperties,
  }

  const parsed = SessionSnapshotSchema.safeParse(payload)
  if (!parsed.success) {
    log(ctx, "error", "snapshot schema validation failed", {
      sessionID,
      errors: parsed.error.issues,
    })
    return
  }

  try {
    await mkdir(dir, { recursive: true })
    const mdContent = buildMarkdown(status, sessionID, parsed.data.eventType, eventProperties)
    const jsonContent = JSON.stringify(parsed.data, null, 2)
    await writeFile(join(dir, `${uuid}.md`), mdContent, "utf-8")
    await writeFile(join(dir, `${uuid}.json`), jsonContent, "utf-8")
    log(ctx, "info", "snapshot written", { sessionID, dir, uuid })
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error)
    log(ctx, "error", "snapshot write failed", { sessionID, reason })
  }
}
