import type { Plugin } from "@opencode-ai/plugin"
import { tool } from "@opencode-ai/plugin"
import { writeFile, mkdir } from "node:fs/promises"
import { join, basename } from "node:path"
import { randomUUID } from "node:crypto"
import { homedir } from "node:os"

const SessionSnapshotSchema = tool.schema.object({
  schemaVersion: tool.schema.string(),
  generatedBy: tool.schema.literal("davercode-session-bridge"),
  generatedAt: tool.schema.string(),
  sessionID: tool.schema.string(),
  eventType: tool.schema.string(),
  projectSlug: tool.schema.string(),
  humanID: tool.schema.string(),
  status: tool.schema.enum(["idle", "error", "completed"]),
  extra: tool.schema.record(tool.schema.string(), tool.schema.unknown()),
})

export const plugin: Plugin = async (ctx) => {
  return {
    event: async (input) => {
      const event = input.event

      if (event.type === "session.created") {
        return log(ctx, "info", "session created", {
          sessionID: event.properties.info.id,
          title: event.properties.info.title,
        })
      }

      if (event.type === "session.idle") {
        await writeSessionSnapshot(ctx, event.properties.sessionID, "idle", event.properties)
        return log(ctx, "info", "session idle", {
          sessionID: event.properties.sessionID,
        })
      }

      if (event.type === "session.error") {
        const sessionID = event.properties.sessionID ?? "unknown"
        await writeSessionSnapshot(ctx, sessionID, "error", event.properties)
        return log(ctx, "error", "session error", {
          sessionID,
          errorType: typeof event.properties.error,
        })
      }

      if (event.type === "session.compacted") {
        return log(ctx, "info", "session compacted", {
          sessionID: event.properties.sessionID,
        })
      }
    },
    tool: {
      session_status: tool({
        description: "List recent opencode sessions with a compact summary",
        args: {
          limit: tool.schema.number().optional().describe("Max sessions to return, defaults to 10"),
        },
        async execute(args, context) {
          try {
            const response = await ctx.client.session.list()
            const sessions = response.data ?? []
            const limit = args.limit ?? 10
            const lines = sessions.slice(0, limit).map((s) => {
              return `${s.id} | ${s.title} | ${new Date(s.time.created).toISOString()}`
            })
            return lines.join("\n")
          } catch (error) {
            const reason = error instanceof Error ? error.message : String(error)
            return `Failed to list sessions: ${reason}`
          }
        },
      }),
    },
  }
}

function log(
  ctx: Parameters<Plugin>[0],
  level: "debug" | "info" | "error" | "warn",
  message: string,
  extra: Record<string, unknown>,
) {
  try {
    ctx.client.app.log({
      body: {
        service: "davercode-session-bridge",
        level,
        message,
        extra,
      },
    }).catch(() => {})
  } catch {
    // structured logging is best-effort: sync throw or unhandled rejection are both swallowed
  }
}

function resolveSnapshotDir(ctx: Parameters<Plugin>[0], dateStamp: string): string {
  const humanID = process.env.OPENCODE_HUMAN_ID ?? process.env.USERNAME ?? process.env.USER ?? "unknown"
  const projectSlug = basename(ctx.directory)
  const home = homedir()
  return join(home, ".config", "opencode", "sessions", humanID, projectSlug, `${dateStamp}-runtime`)
}

function formatDateStamp(): string {
  const now = new Date()
  const dd = String(now.getDate()).padStart(2, "0")
  const mm = String(now.getMonth() + 1).padStart(2, "0")
  const yyyy = String(now.getFullYear())
  return `${dd}${mm}${yyyy}`
}

function buildMarkdown(status: string, sessionID: string, eventType: string, extra: Record<string, unknown>): string {
  const lines = [
    "> Generated by davercode-session-bridge plugin (runtime snapshot)",
    "",
    `# Runtime Snapshot (session ${sessionID})`,
    "",
    "## Status",
    status,
    "",
    "## Decisions",
    "- Not available from runtime event stream",
    "",
    "## Files changed",
    "- Not available from runtime event stream",
    "",
    "## Subagent outcomes",
    "- Not available from runtime event stream",
    "",
    "## Commands run",
    `- Event type: ${eventType}`,
    `- Session ID: ${sessionID}`,
    `- Extra: ${JSON.stringify(extra, null, 2)}`,
    "",
    "## Open questions",
    "- Not available from runtime event stream",
    "",
    "## Resume instructions",
    "- Snapshot generated automatically by davercode-session-bridge plugin",
    "- Consult the session event stream for full context",
  ]
  return lines.join("\n")
}

async function writeSessionSnapshot(
  ctx: Parameters<Plugin>[0],
  sessionID: string,
  status: "idle" | "error" | "completed",
  eventProperties: Record<string, unknown>,
): Promise<void> {
  const dateStamp = formatDateStamp()
  const uuid = randomUUID()
  const dir = resolveSnapshotDir(ctx, dateStamp)
  const projectSlug = basename(ctx.directory)
  const humanID = process.env.OPENCODE_HUMAN_ID ?? process.env.USERNAME ?? process.env.USER ?? "unknown"

  const payload = {
    schemaVersion: "1.0",
    generatedBy: "davercode-session-bridge" as const,
    generatedAt: new Date().toISOString(),
    sessionID,
    eventType: status === "idle" ? "session.idle" : "session.error",
    projectSlug,
    humanID,
    status,
    extra: eventProperties,
  }

  const parsed = SessionSnapshotSchema.safeParse(payload)
  if (!parsed.success) {
    log(ctx, "error", "snapshot schema validation failed", {
      sessionID,
      errors: parsed.error.issues,
    })
    return
  }

  try {
    await mkdir(dir, { recursive: true })
    const mdContent = buildMarkdown(status, sessionID, parsed.data.eventType, eventProperties)
    const jsonContent = JSON.stringify(parsed.data, null, 2)
    await writeFile(join(dir, `${uuid}.md`), mdContent, "utf-8")
    await writeFile(join(dir, `${uuid}.json`), jsonContent, "utf-8")
    log(ctx, "info", "snapshot written", { sessionID, dir, uuid })
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error)
    log(ctx, "error", "snapshot write failed", { sessionID, reason })
  }
}
