[CmdletBinding()]
param(
    [string]$TargetRoot = $(Join-Path $env:USERPROFILE ".config\opencode"),
    [string]$HumanId = $env:USERNAME,
    [string]$ProjectId,
    [string]$RepoPath,
    [switch]$RefreshSessionSnapshot
)

$ErrorActionPreference = "Stop"

$repoRoot = if ($RepoPath) { $RepoPath } else { (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path }
if (-not $ProjectId) {
    $ProjectId = Split-Path -Leaf $repoRoot
}

# Source: docs/project.md (canonical, in repo, version-controlled)
$repoProject = Join-Path $repoRoot "docs\project.md"
$source = Join-Path $TargetRoot "projects\$ProjectId\project.md"
$sessionProject = Join-Path $TargetRoot "sessions\$HumanId\$ProjectId\project.md"
$template = Join-Path $TargetRoot "sessions\_templates\project-session-template.md"

if (-not (Test-Path -LiteralPath $repoProject)) {
    throw "Repo project file not found: $repoProject (expected docs/project.md)"
}

$today = Get-Date -Format "yyyy-MM-dd"
$nextReview = (Get-Date).AddDays(30).ToString("yyyy-MM-dd")
$repoProjectContent = Get-Content -LiteralPath $repoProject -Raw

# Master source: mirror of docs/project.md + review metadata
$sourceContent = @"
# Project Context (Master Source)

> **ROLE**: master source file (mirrors repo's `docs/project.md`)
> **SOURCE REPO**: `$repoRoot/docs/project.md`
> **LAST REVIEWED**: $today
> **NEXT REVIEW DUE**: $nextReview
> **REVIEW CADENCE**: monthly (~30 days)

> This file is auto-generated by `sync-project.ps1`. Do not edit directly.
> Edit `docs/project.md` in the repo and re-run the sync.

$repoProjectContent
"@

$sourceParent = Split-Path -Parent $source
if (-not (Test-Path -LiteralPath $sourceParent)) {
    New-Item -ItemType Directory -Path $sourceParent -Force | Out-Null
}
Set-Content -LiteralPath $source -Value $sourceContent -Encoding UTF8

# Session slang snapshot: created from template on first run or with -RefreshSessionSnapshot
# This is NOT a copy of docs/project.md. It is the project's slang/lunfardo dictionary.
if ((-not (Test-Path -LiteralPath $sessionProject)) -or $RefreshSessionSnapshot) {
    if (-not (Test-Path -LiteralPath $template)) {
        throw "Session template not found: $template"
    }

    $sessionParent = Split-Path -Parent $sessionProject
    if (-not (Test-Path -LiteralPath $sessionParent)) {
        New-Item -ItemType Directory -Path $sessionParent -Force | Out-Null
    }

    $sessionContent = (Get-Content -LiteralPath $template -Raw).
        Replace("{{LAST_REVIEWED}}", $today).
        Replace("{{NEXT_REVIEW_DUE}}", $nextReview).
        Replace("{{SLANG_1}}", "").
        Replace("{{MEANING_1}}", "").
        Replace("{{LOCATION_1}}", "").
        Replace("{{CONFIDENCE_1}}", "").
        Replace("{{SLANG_2}}", "").
        Replace("{{MEANING_2}}", "").
        Replace("{{LOCATION_2}}", "").
        Replace("{{CONFIDENCE_2}}", "").
        Replace("{{SLANG_3}}", "").
        Replace("{{MEANING_3}}", "").
        Replace("{{LOCATION_3}}", "").
        Replace("{{CONFIDENCE_3}}", "")

    Set-Content -LiteralPath $sessionProject -Value $sessionContent -Encoding UTF8
    "Updated source and refreshed session slang snapshot"
} else {
    "Updated source only; existing session slang snapshot kept"
}
